# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3f35a623dfc6468a4ac639940d4f40efa97d74e65303938501dbc2c2fd9ff06d794384f1f2db19604755e3359e7e0ed8eb85c15d51e502b46588e3cc980e51

test:
  secret_key_base: 8a6c56d9e3992430085add429d357bf8b839ff4fb58d44fe70f9fb6d8befcdf292bb156b5025c69ce89781b76c22a03f9739185d4c42ef16840abc4326e6baff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
